version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app-container
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - flask-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
